{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "sample.serviceAccountName" . }}
  labels:
{{ include "sample.labels" . | indent 4 }}
{{- end -}}
